### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by 20cameronw** [20cameronw/spheerRepo#8]
- [ ] Merge/Create Prefabs
- [ ] Main Menu UI
- [x] Shop UI
- [ ] Worlds Shop UI
- [x] Color all objects
- [ ] Improve Turret code
- [ ] Create Special Effects 
- [ ] Make list of research upgrades
- [ ] Remake scriptable object scripts
- [x] Create Shop Card Template
- [ ] Improve the progression of upgrades
- [ ] Create Prestige system and currency
- [x] Create Shop Manager script that controls the overall state of the UI
- [ ] Sound Effects
- [ ] Improve Enemy AI
- [ ] Create Shaders for atmosphere, prefabs, etc.
- [x] Recruit Jarrett Brattin for design/effects/art/logic/tester
- [ ] Review and test all source code
- [ ] Make custom editor scripts to make editing the game flow easier
- [ ] Add background music
